# Generated by Django 5.2.7 on 2025-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('descicao', models.CharField(max_length=300)),
                ('email', models.CharField(unique=True)),
            ],
        ),
    ]
