# Generated by Django 5.2.7 on 2025-10-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desenvolvedor',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
