# Generated by Django 5.2.7 on 2025-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_descicao_desenvolvedor_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(unique=True)),
                ('assunto', models.CharField(max_length=300)),
                ('mensagem', models.CharField(max_length=300)),
            ],
        ),
    ]
